spring:
  application:
    name: lecture
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:lectureDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
      hibernate.type:
        descriptor.sql.BasicBinder: trace
